// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgQYhn-BZJyWCNFXyIzmIgrQzcOwHfFJM',
    appId: '1:108836461714:web:79b42a85e3352a46871a4b',
    messagingSenderId: '108836461714',
    projectId: 'projet-object-finder',
    authDomain: 'projet-object-finder.firebaseapp.com',
    storageBucket: 'projet-object-finder.firebasestorage.app',
    measurementId: 'G-PGSVMT4SBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe89MdsHmL0JLFjhTolLIAxE-8i-0KU-o',
    appId: '1:108836461714:android:ad8d61f04880964b871a4b',
    messagingSenderId: '108836461714',
    projectId: 'projet-object-finder',
    storageBucket: 'projet-object-finder.firebasestorage.app',
    authDomain: 'projet-object-finder.firebaseapp.com',
);

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1kNqiR3h9TPy396ms5YBgbjTYvg8sP4M',
    appId: '1:108836461714:ios:46a9b079938ecb59871a4b',
    messagingSenderId: '108836461714',
    projectId: 'projet-object-finder',
    storageBucket: 'projet-object-finder.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1kNqiR3h9TPy396ms5YBgbjTYvg8sP4M',
    appId: '1:108836461714:ios:46a9b079938ecb59871a4b',
    messagingSenderId: '108836461714',
    projectId: 'projet-object-finder',
    storageBucket: 'projet-object-finder.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgQYhn-BZJyWCNFXyIzmIgrQzcOwHfFJM',
    appId: '1:108836461714:web:b994538430936b0c871a4b',
    messagingSenderId: '108836461714',
    projectId: 'projet-object-finder',
    authDomain: 'projet-object-finder.firebaseapp.com',
    storageBucket: 'projet-object-finder.firebasestorage.app',
    measurementId: 'G-XZZB74XFWY',
  );
}
